version: '3.4'

services:
  inteligentprivatefinance:
    image: inteligentprivatefinance
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
      - 8080:8080
