USE [master]
GO

-- evolve-tx-off
CREATE DATABASE [DespesasPessoaisDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DespesasPessoaisDB', FILENAME = N'/var/opt/mssql/data/DespesasPessoaisDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DespesasPessoaisDB_log', FILENAME = N'/var/opt/mssql/data/DespesasPessoaisDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

ALTER DATABASE [DespesasPessoaisDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DespesasPessoaisDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DespesasPessoaisDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DespesasPessoaisDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DespesasPessoaisDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [DespesasPessoaisDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DespesasPessoaisDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DespesasPessoaisDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DespesasPessoaisDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DespesasPessoaisDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DespesasPessoaisDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DespesasPessoaisDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DespesasPessoaisDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DespesasPessoaisDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DespesasPessoaisDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DespesasPessoaisDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DespesasPessoaisDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DespesasPessoaisDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DespesasPessoaisDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DespesasPessoaisDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DespesasPessoaisDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DespesasPessoaisDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DespesasPessoaisDB] SET RECOVERY FULL 
GO

ALTER DATABASE [DespesasPessoaisDB] SET  MULTI_USER 
GO

ALTER DATABASE [DespesasPessoaisDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DespesasPessoaisDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DespesasPessoaisDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DespesasPessoaisDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DespesasPessoaisDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DespesasPessoaisDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DespesasPessoaisDB] SET  READ_WRITE 
GO
